version: '2'

services:

  stt:
    build:
      context: .
      dockerfile: stt/Dockerfile
    container_name: voice_note_stt
    environment:
      CHAT_URI: ws://chat:12346
    ports:
      - 12345:12345
    volumes:
      - ../models/whisper-medium:/usr/src/app/models/whisper-medium:ro
      - ../logs:/usr/src/app/logs
      - ../outputs:/usr/src/app/outputs
    user: 1000:1000
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - voice_note_net

  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: voice_note_chat
    environment:
      CHAT_AGENT_CWD: /workspace
      LLAMACPP_BASE_URL: http://llamacpp:8080/v1
      TTS_URI: ws://tts:12347
    volumes:
      - ../logs:/usr/src/app/logs
      - ../pi-agent:/usr/src/app/pi-agent
      - ../..:/workspace
    expose:
      - 12346
    depends_on:
      - llamacpp
      - tts
    user: 1000:1000
    networks:
      - voice_note_net

  llamacpp:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda13
    container_name: voice_note_llamacpp
    command:
      - --host
      - 0.0.0.0
      - --port
      - "8080"
      - --model
      - /models/gemma-4-12b-it-UD-Q6_K_XL.gguf
      - --alias
      - gemma-4-12B
      - --ctx-size
      - "65536"
    volumes:
      - ../models/chat/gemma-4-12b-it-GGUF:/models:ro
      - ../logs:/usr/src/app/logs
    expose:
      - 8080
    ports:
      - 8080:8080
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - voice_note_net

  tts:
    build:
      context: .
      dockerfile: tts/Dockerfile
    container_name: voice_note_tts
    volumes:
      - ../models/tts-1.6b-en_fr:/usr/src/app/models/tts-1.6b-en_fr:ro
      - ../models/tts-voices:/usr/src/app/models/tts-voices:ro
      - ../logs:/usr/src/app/logs
    expose:
      - 12347
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - voice_note_net

networks:
  voice_note_net:
