version: '2'

services:

  stt:
    build:
      context: .
      dockerfile: stt/Dockerfile
    container_name: voice_note_stt
    ports:
      - 12345:12345
    volumes:
      - ../models/whisper-medium:/usr/src/app/models/whisper-medium:ro
      - ../logs:/usr/src/app/logs
      - ../outputs:/usr/src/app/outputs
    user: 1000:1000  # Same user as on host, so the created files have the same owner.
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - voice_note_net

  chat:
    build:
      context: .
      dockerfile: chat/Dockerfile
    container_name: voice_note_chat
    volumes:
      - ../models/chat/Qwen3-8B-FP8:/usr/src/app/models/chat/Qwen3-8B-FP8:ro
      - ../logs:/usr/src/app/logs
    expose:
      - 12346
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - voice_note_net

  tts:
    build:
      context: .
      dockerfile: tts/Dockerfile
    container_name: voice_note_tts
    volumes:
      - ../models/tts-1.6b-en_fr:/usr/src/app/models/tts-1.6b-en_fr:ro
      - ../models/tts-voices:/usr/src/app/models/tts-voices:ro
      - ../logs:/usr/src/app/logs
    expose:
      - 12347
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    networks:
      - voice_note_net

networks:
  voice_note_net:
